Update create-redocly.yaml

diff --git a/.github/workflows/create-redocly.yaml b/.github/workflows/create-redocly.yaml
--- a/.github/workflows/create-redocly.yaml
+++ b/.github/workflows/create-redocly.yaml
@@ -7,25 +7,8 @@ on:
   pull_request:
 
 jobs:
+
   test_job:
-    runs-on: ubuntu-latest
-    name: Testing private usage
-    steps:
-      # To use this repository's private action, you must check out the repository
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: redoc-cli test
-        uses: ./ # Uses an action in the root directory
-        with:
-          args: 'bundle utm.yaml -o petstore.html'
-
-      - name: check result
-        run: |
-          ls -al
-          test -f petstore.html || (echo "Missing petstore.html from previous step." && exit 1)
-
-  test_job_2:
     runs-on: ubuntu-latest
     name: Testing public name
     steps:
@@ -34,6 +17,24 @@ jobs:
 
       # use the public name of the action
       - name: redoc-cli test
+        uses: seeebiii/redoc-cli-github-action@v10
+        with:
+          args: 'bundle utm.yaml -o petstore.html'
+
+      - name: check result
+        run: |
+          ls -al
+          test -f petstore.html || (echo "Missing petstore.html from previous step." && exit 1)
+
+  generate_html:
+    runs-on: ubuntu-latest
+    name: Generate static HTML
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      # use the public name of the action
+      - name: redoc-cli bundle
         uses: seeebiii/redoc-cli-github-action@v10
         with:
           args: 'bundle utm.yaml -o petstore.html'
